// Code generated by struct-to-pflags; DO NOT EDIT.

package example

import (
	"github.com/spf13/pflag"
)

const (
	flagLogFile = "log-file"
	flagDebug   = "debug"
	flagPort    = "port"
)

func withConfigFlags(flags *pflag.FlagSet) {
	flags.String(flagLogFile, defaultConfig.logFile, "path to file where logs will be written")
	flags.Bool(flagDebug, defaultConfig.debug, "enable debug mode")
	flags.Int(flagPort, defaultConfig.port, "port number to listen on")
}

func loadConfig(flags *pflag.FlagSet, version string) (*config, error) {
	logFile, err := flags.GetString(flagLogFile)
	if err != nil {
		return nil, err
	}

	debug, err := flags.GetBool(flagDebug)
	if err != nil {
		return nil, err
	}

	port, err := flags.GetInt(flagPort)
	if err != nil {
		return nil, err
	}

	return &config{
		logFile: logFile,
		debug:   debug,
		port:    port,
		version: version,
	}, nil
}
